version: '3'

services:
  postgres:
    container_name: social-postgres
    image: postgres:14
    environment:
      POSTGRES_DB: social-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  social_api:
    container_name: social-api
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
