spring:
  liquibase:
    url: jdbc:postgresql://postgres:5432/social-postgres
    user: postgres
    password: root
    change-log: classpath:/db/changelog/db.changelog-master.xml
    clear-checksums: true
  datasource:
    url: jdbc:postgresql://postgres:5432/social-postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
  data:
    web:
      pageable:
        max-page-size: 100

profiling:
  enable: false

server:
  port: 8080

social:
  media:
    jwt:
      secret:
        =======================SocialMediaApi===========================
      expirationMs:
        3600000
      cookieName:
        jwt

springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    enabled: true
    url: /v3/api-docs


image:
  resource:
    get:
      url:
        http://localhost:${server.port}/api/v1/images/
logging:
  level:
    root: info
